// AUTOGENERATED, DO NOT EDIT MANUALLY
// @see tooling/icon-generator

import { ReactComponent as arrowDownIcon } from './static/svg/arrow-down.svg'

export const Icons = { arrowDownIcon }

export type Icon = keyof typeof Icons
